controller_manager:
  ros__parameters:
    gripper_controller:
      type: position_controllers/JointGroupPositionController

gripper_controller:
  ros__parameters:
    type: position_controllers/JointGroupPositionController
    joints:
      - gripper_ef1_base_joint
      - gripper_ef2_base_joint
    command_interfaces: ["position"]
    state_interfaces: ["position"]
    allow_stalling: true
    publish_rate: 20
    qos:
      commands:
        reliability: reliable
        durability: volatile
    